---
title: "Weighted Gene Coexpression Network Analysis"
output: html_notebook
---
```{r message=FALSE}
###loading libraries for entire analysis

# BiocManager::install("impute")

library("WGCNA")
library(cluster)
allowWGCNAThreads()
options(stringsAsFactors = FALSE)
library(readr)
library(readxl)
library(tidyr)     
library(ggplot2) 
library(plyr) 
library(dplyr)
```

```{r}
### setup working directory

setwd("~/Library/Mobile Documents/com~apple~CloudDocs/Documents/WPI/Young/data")
```

```{r}
### loading expression data
yl_norm_counts = read.delim("yl/output/norm_counts.txt")
yl_norm_counts$proteinId <- row.names(yl_norm_counts)
```

```{r}
### load DEGs
yl_contrastDEGenes = read_csv("yl/output/unique_contrastDEGenes_yl.csv")
sig_degs_.95 = yl_contrastDEGenes[which(yl_contrastDEGenes$padj <= 0.95),]
sig_degs_up = yl_contrastDEGenes[which(yl_contrastDEGenes$log2FoldChange >= 1),]
sig_degs_down = yl_contrastDEGenes[which(yl_contrastDEGenes$log2FoldChange <= -1),]
sig_degs = rbind(sig_degs_up, sig_degs_down)
```

```{r}
yl_deg_counts = merge(yl_norm_counts, sig_degs, by = "proteinId")
yl_sig_counts = yl_deg_counts[,-c(14:20)]
write.csv(yl_sig_counts, "~/Library/Mobile Documents/com~apple~CloudDocs/Documents/WPI/Young/data/comparative_dh/output/sigDEGS_yl.csv")
```

```{r}
yldatexp = as.data.frame(t(yl_sig_counts[,-1])) #transpose data
names(yldatexp) = rownames(yl_sig_counts)
rownames(yldatexp) = names(yl_sig_counts[,-1])
dim(yldatexp)
```

```{r}
gsg = goodSamplesGenes(yldatexp, verbose = 3);
gsg$allOK
```

```{r}
ylsampleTree = hclust(dist(yldatexp), method = "average");
# Plot the sample tree: Open a graphic output window of size 12 by 9 inches
# The user should change the dimensions if the window is too large or too small.
sizeGrWindow(12,9)
#pdf(file = "Plots/sampleClustering.pdf", width = 12, height = 9);
par(cex = 0.6);
par(mar = c(0,4,2,0))
plot(ylsampleTree, main = "Sample clustering to detect outliers", ylab="", xlab="", cex.lab = 1.5,
     cex.axis = 1.5, cex.main = 2)
```

```{r}
# Choose a set of soft-thresholding powers
powers = c(c(1:10), seq(from = 12, to=20, by=2))
# Call the network topology analysis function
# sft_yl = pickSoftThreshold(yldatexp, powerVector = powers, verbose = 5)
# save(sft_yl, file = "comparative_dh/output/yl/sft_yl.RData")
load("comparative_dh/output/yl/sft_yl.RData")
# Plot the results:
sizeGrWindow(9, 5)
par(mfrow = c(1,2));
cex1 = 0.9;
# Scale-free topology fit index as a function of the soft-thresholding power
plot(sft_yl$fitIndices[,1], -sign(sft_yl$fitIndices[,3])*sft_yl$fitIndices[,2],
xlab="Soft Threshold (power)",ylab="Scale Free Topology Model Fit,signed R^2",type="n",
main = paste("Scale independence"));
text(sft_yl$fitIndices[,1], -sign(sft_yl$fitIndices[,3])*sft_yl$fitIndices[,2],
labels=powers,cex=cex1,col="red");
# this line corresponyl to using an R^2 cut-off of h
abline(h=0.90,col="red")
# Mean connectivity as a function of the soft-thresholding power
plot(sft_yl$fitIndices[,1], sft_yl$fitIndices[,5],
xlab="Soft Threshold (power)",ylab="Mean Connectivity", type="n",
main = paste("Mean connectivity"))
text(sft_yl$fitIndices[,1], sft_yl$fitIndices[,5], labels=powers, cex=cex1,col="red")

# power = 12, R^2 = 0.9
```

```{r}
net_yl = blockwiseModules(yldatexp, power = 20, 
                       corType = "pearson", 
                       networkType = "signed", 
                       minModuleSize = 30,
                       reassignThreshold = 0, 
                       mergeCutHeight = 0.25,
                       numericLabels = TRUE, 
                       pamRespectsDendro = FALSE,
                       saveTOMs = FALSE, 
                       verbose = 3)
save(net_yl, file = "comparative_dh/output/yl/net_yl.RData")

load("comparative_dh/output/yl/net_yl.RData")
```


```{r}
table(net_yl$colors)
```


```{r}
# open a graphics window
sizeGrWindow(12, 9)
# Convert labels to colors for plotting
mergedColors = labels2colors(net_yl$colors)
# Plot the dendrogram and the module colors underneath
plotDendroAndColors(net_yl$dendrograms[[1]], 
                    mergedColors[net_yl$blockGenes[[1]]], "Module colors",
                    dendroLabels = FALSE, hang = 0.03,
                    addGuide = TRUE, guideHang = 0.05)
```


```{r}
ylmoduleLabels = net_yl$colors
ylmoduleColors = labels2colors(net_yl$colors) ; table(ylmoduleColors)
ylMEs = net_yl$MEs;
ylgeneTree = net_yl$dendrograms[[1]];
save(ylMEs, ylmoduleLabels, ylmoduleColors, ylgeneTree,
file = "comparative_dh/output/yl/yl-networkConstruction-auto.RData")
```

# Part 5: Visualization of Networks
```{r}
# Calculate topological overlap anew: this could be done more efficiently by saving the TOM
# calculated during module detection, but let us do it again here.
yldissTOM = 1-TOMsimilarityFromExpr(yldatexp, power = 20);
# Transform dissTOM with a power to make moderately strong connections more visible in the heatmap
ylplotTOM = yldissTOM^16;
# Set diagonal to NA for a nicer plot
diag(ylplotTOM) = NA;
# Call the plot function
sizeGrWindow(9,9)
png("comparative_dh/output/yl/yl-network.pdf")
print(TOMplot(ylplotTOM, ylgeneTree, ylmoduleColors, main = "Network heatmap plot"))
dev.off()
```

```{r}
ylnGenes = ncol(yldatexp)
ylnSamples = nrow(yldatexp)

nSelect = 100
# For reproducibility, we set the random seed
set.seed(10);
ylselect = sample(ylnGenes, size = nSelect);
ylselectTOM = yldissTOM[ylselect, ylselect];
# There’s no simple way of restricting a clustering tree to a subset of genes, so we must re-cluster.
ylselectTree = hclust(as.dist(ylselectTOM), method = "average")
ylselectColors = ylmoduleColors[ylselect];
# Open a graphical window
sizeGrWindow(9,9)
# Taking the dissimilarity to a power, say 10, makes the plot more informative by effectively changing
# the color palette; setting the diagonal to NA also improves the clarity of the plot
ylplotDiss = ylselectTOM^7;
diag(ylplotDiss) = NA;
png("comparative_dh/output/yl/yl-network.png")
print(TOMplot(ylplotDiss, ylselectTree, ylselectColors, main = "Network heatmap plot"))
dev.off()
```

```{r}
# Recalculate module eigengenes
ylMEs = moduleEigengenes(yldatexp, ylmoduleColors)$eigengenes
ylMET = orderMEs(ylMEs)
# Plot the relationships among the eigengenes and the trait
sizeGrWindow(5,7.5);
par(cex = 0.9)
plotEigengeneNetworks(ylMET, "", marDendro = c(0,4,1,2), marHeatmap = c(3,4,1,2), cex.lab = 0.8, xLabelsAngle = 90)
```

```{r}
# Plot the dendrogram
sizeGrWindow(6,6);
par(cex = 1.0)
plotEigengeneNetworks(ylMET, "Eigengene dendrogram", marDendro = c(0,4,2,0),
plotHeatmaps = FALSE)
# Plot the heatmap matrix (note: this plot will overwrite the dendrogram plot)
par(cex = 1.0)
plotEigengeneNetworks(ylMET, "Eigengene adjacency heatmap", marHeatmap = c(3,4,2,2),
plotDendrograms = FALSE, xLabelsAngle = 90)
```


```{r}
### trend analysis

ylgeneModuleMembership = as.data.frame(cor(yldatexp, ylMEs, use = "p"));
ylmodule_colors = data.frame(ylmoduleColors)
ylcounts <- cbind(yl_sig_counts,ylmodule_colors)
yldata = data.frame(t(ylcounts))
ylcolors = unique(ylcounts$ylmoduleColors)

ylMM_counts = cbind(ylcounts,ylgeneModuleMembership)


write.csv(ylMM_counts, file = "comparative_dh/output/yl/MM_yl_counts.csv")

```

```{r}
annotations = read_csv("~/Library/Mobile Documents/com~apple~CloudDocs/Documents/WPI/Young/data/yl/output/jgi_ergo_annotation_yl.csv")
annotations = annotations[,-c(1,3)]

MM_annotation = merge(ylMM_counts, annotations, by = "proteinId")
write.csv(MM_annotation, file = "comparative_dh/output/MM_yl_counts_annotation.csv")
```


```{r}
for (i in ylcolors){
  
  print(i)
  
  s = subset(ylcounts, grepl(i, yldata), proteinId:lowFE.2)
  n <- nrow(s)
  
  module.dist.df.long = gather(s, ylmodule_colors, ylcounts, cont:lowFE.2)
  names(module.dist.df.long) <- c("proteinId", "genotype", "count")
  
  
  plot.tmp = ggplot(data = module.dist.df.long, aes(x = genotype, y = count, group = proteinId)) +
    geom_line()  +
    theme(text = element_text(size = 20)) +
    geom_line(data = module.dist.df.long %>% group_by(genotype) %>% summarize(count = mean(count)),
              aes(group = 2), size = 1.25, color = "red") +
    geom_line(data = module.dist.df.long %>% group_by(genotype) %>% summarize(count = median(count)),
              aes(group = 2), size = 1.25, color = "blue") +
    scale_y_continuous(trans="log10") +
    #labs(title = paste("module:",i,"number of transcripts:",n, sep = "\n")) +
    labs(title = paste(i,n, sep = "\n")) +
    theme(plot.title = element_text(size = 50)) +
    theme(plot.title = element_text(hjust = 0.5)) +
    theme(axis.text = element_text(size = 20))
  
  
  filename_ggplot = paste("comparative_dh/output/yl/MM_yl_counts_",i,".eps", sep = "")
  postscript(filename_ggplot, width = 1000, height = 1000)
  print(plot.tmp)
  dev.off()
  
}
```

```{r}
yldatME=moduleEigengenes(yldatexp,ylmoduleColors)$eigengenes
signif(cor(yldatME, use="p"), 2)

dissimME=(1-t(cor(yldatME, method="p")))/2
hclustdatME=hclust(as.dist(dissimME), method="average" )
# Plot the eigengene dendrogram
par(mfrow=c(1,1))
plot(hclustdatME, main="Clustering tree based of the module eigengenes")

for (i in ylcolors){

  s = subset(ylcounts, grepl(i, yldata), proteinId:lowFE.2)
  n <- nrow(s)

  sizeGrWindow(8,7);
  which.module=i
  ylME=yldatME[, paste("ME",which.module, sep="")]
  
  MM_filename = paste("comparative_dh/output/yl/MM_heat_yl_",i,".eps", sep = "")
  postscript(MM_filename , width = 1000, height = 1000, pointsize = 15)
  
  par(mfrow=c(2,1), mar=c(0.3, 5.5, 3, 2))
  plotMat(t(scale(yldatexp[,ylmoduleColors==which.module ]) ),
          nrgcols=30,rlabels=F,rcols=which.module,
          main=paste(i,n, sep = " - "), cex.main=2)
  
  dev.off()
  
  MM_filename = paste("comparative_dh/output/yl/MM_bar_yl_",i,".eps", sep = "") 
  postscript(MM_filename, width = 1000, height = 1000, pointsize = 15)
  
  par(mar=c(5, 4.2, 2, 0.7))
  barplot(ylME, col=which.module, main="", cex.main=2, horiz = F,  ylim = c(-.4, .9),
          ylab="eigengene expression",xlab="array sample",axisnames = T, names.arg = c( "cont", "cont", "cont", "lowN", "lowN", "lowN", "salt", "salt", "salt", "lowFE", "lowFE", "lowFE"))
  
  dev.off()
}
```

```{r}
ADJ1=abs(cor(datExpr,use="p"))^6
Alldegrees1=intramodularConnectivity(ADJ1, colorh1)
head(Alldegrees1)
```


